### PR TITLE
add reason for joining and name columns to user's table

### PR DESCRIPTION
**Pull request by timothykiyeng**

### CODE REVIEW

**Comment by timothykiyeng** [comment]
@otsembo Can this be merged to development so that @Muriithi-Gitonga and @mackrineawino can work with it?

**Review by otsembo — APPROVED** [review]
Everything looks good to me @timothykiyeng 

@chelahcynthia @cynthiamoraa Kindly make your reviews.

**Review by chelahcynthia — COMMENTED** [review]
All the changes made are okay. Everything looks okay.

**Review by cynthiamoraa — APPROVED** [review]
Everything works well

**Pull request merged**
