### PR TITLE
mitch-ian/#80/app_installation

### LINKED ISSUE #80: app installation
Fix app installation error.

- [x] The app currently considers every app as already installed even for new users.
- [x] It also needs to navigate to login after the splash screen loads if the app has been installed.
- [ ] Make the logo animate so as to inform the users on the web that it is currently loading
- [ ] Scale registration pages to larger screens

### PR DESCRIPTION
**Pull request by otsembo**
This PR contains the following:

- [x] Fixed the installation error when the app did not recognize a user had installed and kept showing the splash screens
- [x] Add responsive sign-up pages in alternate formats.

Hello @jbdura , @timothykiyeng Kindly make reviews on this.

### CODE REVIEW

**Comment by timothykiyeng** [comment]
@Mitchell-Ngetich @otsembo I noticed steps 3 and 4 are disimillar to pages 1 & 2

Screenshot from 2023-07-03 17-22-04
Screenshot from 2023-07-03 16-24-41
Screenshot from 2023-07-03 16-24-25

**Review by timothykiyeng — CHANGES_REQUESTED** [review]
Great job, Mitchell and Ian. Kindly check on the above

**Comment by Mitchell-Ngetich** [comment]
@timothykiyeng I have made changes. Kindly review

**Review by timothykiyeng — COMMENTED** [review]
Now, it looks good to me.

**Pull request merged**
