### PR TITLE
Bdura docker fix

### PR DESCRIPTION
**Pull request by jbdura**
Made migrations of fields is_active and is_deleted in the user. created delete_user.rb handling deletion mutation

### CODE REVIEW

**Review by otsembo — CHANGES_REQUESTED** [review]
Hello @jbdura you have some failing checks in your PR. Kindly fix them out first.

**Comment by jbdura** [comment]
docker-compose.prod.yml edits.
user delete feature added. Added fields in user_type.rb and added delete_user.rb in mutation

**Review by timothykiyeng — CHANGES_REQUESTED** [review]
Looks good @jbdura Now, add relevant tests for the feature.

**Review by otsembo — CHANGES_REQUESTED** [review]
Hello @jbdura @chelahcynthia There is a merge conflict in your schema file.
Kindly fix this first.

**Comment by jbdura** [comment]
The conflicts are because of different migrations and addition of our fields. Should I pull and push again?

**Comment by mackrineawino** [comment]
> The conflicts are because of different migrations and addition of our fields. Should I pull and push again?

@jbdura some additional fields(name and reason for joining) were added to the schema yesterday...I think you should have pulled them. That might be the cause of the conflict because your version is missing those.

**Comment by jbdura** [comment]
conflict fixed

**Comment by chelahcynthia** [comment]
> Looks good @jbdura Now, add relevant tests for the feature.

Working on it!

**Pull request closed without merging**
