### PR TITLE
mitch-ian/graphql documentation

### PR DESCRIPTION
**Pull request by otsembo**
This pull request contains the following:

- [ ] A new file known as `graphql.md` was added.
- [ ] Markdown for all GraphQL Server mutations

Hello @mackrineawino , @Muriithi-Gitonga Kindly make a review of the PR.

### CODE REVIEW

**Review by Muriithi-Gitonga — CHANGES_REQUESTED** [review]
Hello @otsembo @Mitchell-Ngetich Great Job on the PR
However there is a small typo on the word "Response" it is missing letter p
image

**Review by mackrineawino — APPROVED** [review]
@otsembo , @Mitchell Everything looks good. You can go ahead and merge the pr once @Muriithi-Gitonga approves.

**Comment by otsembo** [comment]
Hello @Muriithi-Gitonga I have made the changes. Kindly review.

**Comment by Muriithi-Gitonga** [comment]
Everything looks good @Mitchell-Ngetich  @otsembo
You can merge the PR

**Review by Muriithi-Gitonga — APPROVED** [review]
Everything looks good @Mitchell-Ngetich @otsembo 
You can merge the PR

**Pull request merged**
